import time
import uuid
import logging
from contextlib import asynccontextmanager
from pathlib import Path

# Sentry must be initialized before other imports
from app.config import ENV, API_VERSION, APP_NAME, ALLOWED_ORIGINS, PILOTOS_ENABLED, PILOTOS_PORT, ADMIN_SECRET, DEMO_RATE_LIMIT
_sentry_dsn = __import__("os").getenv("SENTRY_DSN", "")
if _sentry_dsn:
    import sentry_sdk
    sentry_sdk.init(
        dsn=_sentry_dsn,
        environment=ENV,
        traces_sample_rate=0.1,
        send_default_pii=False,
    )

from fastapi import FastAPI, APIRouter, Query, HTTPException, Depends, Request
from fastapi.exceptions import RequestValidationError
from starlette.exceptions import HTTPException as StarletteHTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from app.quantum_engine import QuantumEngine, VALID_BACKENDS
from app.auth import require_api_key, get_ratelimit_info, TIER_LIMITS
from app.database import (
    create_api_key,
    log_usage,
    update_last_used,
    get_usage_stats,
    check_connection,
    list_all_keys,
    deactivate_api_key,
    reactivate_api_key,
    update_api_key_tier,
    rotate_api_key,
    get_dashboard_stats,
    get_usage_logs,
    update_allowed_ips,
    enable_signing,
    disable_signing,
    migrate_plaintext_keys,
    purge_old_usage_logs,
)

logger = logging.getLogger("quantumrand")
logging.basicConfig(level=logging.INFO, format="%(message)s")


# --- Demo rate limiter (in-memory, per IP) ---
import threading as _threading
_demo_hits: dict[str, list[float]] = {}
_demo_lock = _threading.Lock()


def _check_demo_rate(ip: str) -> bool:
    """Return True if IP is within demo rate limit."""
    now = time.time()
    window = 60.0  # 1 minute
    with _demo_lock:
        hits = _demo_hits.get(ip, [])
        hits = [t for t in hits if now - t < window]
        if len(hits) >= DEMO_RATE_LIMIT:
            _demo_hits[ip] = hits
            return False
        hits.append(now)
        _demo_hits[ip] = hits
        return True


def _validate_webhook_url(url: str):
    """Block SSRF: reject private/internal IPs and non-HTTPS URLs."""
    if not url.startswith("https://"):
        raise HTTPException(status_code=400, detail="callback_url must use HTTPS")
    from urllib.parse import urlparse
    import ipaddress
    import socket
    parsed = urlparse(url)
    hostname = parsed.hostname
    if not hostname:
        raise HTTPException(status_code=400, detail="Invalid callback URL")
    # Block obvious internal hostnames
    blocked = {"localhost", "127.0.0.1", "0.0.0.0", "::1", "[::1]"}
    if hostname in blocked:
        raise HTTPException(status_code=400, detail="callback_url cannot target localhost")
    # Resolve and check for private IPs
    try:
        resolved = socket.getaddrinfo(hostname, None, socket.AF_UNSPEC, socket.SOCK_STREAM)
        for _, _, _, _, addr in resolved:
            ip = ipaddress.ip_address(addr[0])
            if ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved:
                raise HTTPException(status_code=400, detail="callback_url cannot target private/internal networks")
    except socket.gaierror:
        raise HTTPException(status_code=400, detail="Could not resolve callback URL hostname")


def _require_admin(secret: str):
    """Validate admin secret, raise 403/404 if invalid or not configured."""
    if ADMIN_SECRET is None:
        raise HTTPException(status_code=404, detail="Not found")
    if secret != ADMIN_SECRET:
        raise HTTPException(status_code=403, detail="Invalid admin secret")


def _schedule_purge():
    """Run purge_old_usage_logs, log the result, then re-schedule itself for 24 hours later."""
    try:
        deleted = purge_old_usage_logs()
        logger.info(f"Usage log auto-purge: deleted {deleted} documents older than 90 days")
    except Exception as e:
        logger.warning(f"Usage log auto-purge failed: {e}")
    t = _threading.Timer(86400, _schedule_purge)
    t.daemon = True
    t.start()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Start embedded quantum simulator on boot if Origin backend is enabled."""
    if PILOTOS_ENABLED:
        try:
            from simulator.launcher import start_simulator, stop_simulator
            start_simulator(port=PILOTOS_PORT)
            logger.info("Embedded quantum simulator started")
        except Exception as e:
            logger.warning(f"Could not start embedded simulator: {e}")
    start_pool()
    _schedule_purge()
    yield
    if PILOTOS_ENABLED:
        try:
            from simulator.launcher import stop_simulator
            stop_simulator()
        except Exception:
            pass

START_TIME = time.time()

API_DESCRIPTION = """
## Welcome to QuantumRand API

True quantum randomness as a service. Every number generated by this API is decided by quantum physics — not mathematical formulas.

### Quick Start
1. Create a free API key via **POST /keys/create**
2. Click **Authorize** above and paste your key
3. Call any **/generate/** endpoint

### Authentication
All /generate/ endpoints require an API key in the header: `X-API-Key: qr_your_key_here`

### Tiers
| Tier | Price | Calls/Day | Max Bits |
|------|-------|-----------|----------|
| Free | $0 | 100 | 256 |
| Indie | $9/mo | 1,000 | 1,024 |
| Startup | $49/mo | 10,000 | 2,048 |
| Business | $299/mo | 100,000 | 4,096 |

### Backends
| Backend | Provider | Type | Max Qubits |
|---------|----------|------|------------|
| `aer_simulator` | Qiskit | Local simulator | 1024 |
| `origin_cloud` | Origin Quantum | Cloud simulator | 20 |
| `origin_wuyuan` | Origin Quantum | Real quantum chip | 20 |
| `ibm_hardware` | IBM Quantum | Real quantum chip | 127 |

Pass `?backend=ibm_hardware` to any /generate/ endpoint to use real IBM quantum hardware (queued, 2-30 min).
Pass `?backend=aer_simulator` for instant results from a local quantum simulator.

### How It Works
Quantum bits are placed in superposition using Hadamard gates. When measured, physics — not math — decides the outcome. This produces randomness that is fundamentally unpredictable.
"""

CUSTOM_CSS = """
/* QuantumRand Dark Docs Theme — Complete */
*,*::before,*::after { box-sizing: border-box; }
html, body { background: #09090b !important; color: #e4e4e7 !important; }

.swagger-ui {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif !important;
    color: #e4e4e7 !important;
}

/* ── Topbar ── */
.swagger-ui .topbar { display: none !important; }

/* ── Global dark backgrounds ── */
.swagger-ui,
.swagger-ui .scheme-container,
.swagger-ui .info,
.swagger-ui .opblock-tag-section,
.swagger-ui .wrapper,
.swagger-ui .models,
.swagger-ui section.models { background: #09090b !important; }

/* ── Info header ── */
.swagger-ui .info .title { color: #6d9eff !important; font-size: 2em !important; font-weight: 700 !important; }
.swagger-ui .info .description,
.swagger-ui .info .description p,
.swagger-ui .info .description li { color: #a1a1aa !important; line-height: 1.7 !important; }
.swagger-ui .info .description h2,
.swagger-ui .info .description h3 { color: #fafafa !important; margin-top: 1.5em !important; }
.swagger-ui .info .description code {
    background: #18181b !important; color: #6d9eff !important;
    padding: 2px 6px !important; border-radius: 4px !important;
    font-family: 'JetBrains Mono', monospace !important; font-size: 0.9em !important;
}
.swagger-ui .info .description a { color: #6d9eff !important; text-decoration: underline !important; }
.swagger-ui .info .description a:hover { color: #93b4ff !important; }

/* ── Tables in description ── */
.swagger-ui .info .description table { border-collapse: collapse !important; width: 100% !important; margin: 16px 0 !important; }
.swagger-ui .info .description th {
    background: #18181b !important; color: #6d9eff !important;
    padding: 10px 14px !important; border: 1px solid #27272a !important; text-align: left !important;
}
.swagger-ui .info .description td {
    background: #111113 !important; color: #a1a1aa !important;
    padding: 8px 14px !important; border: 1px solid #27272a !important;
}

/* ── Authorize button ── */
.swagger-ui .btn.authorize {
    background: #6d9eff !important; color: #09090b !important; border: none !important;
    border-radius: 6px !important; font-weight: 600 !important; padding: 8px 20px !important;
}
.swagger-ui .btn.authorize:hover { background: #93b4ff !important; }
.swagger-ui .btn.authorize svg { fill: #09090b !important; }
.swagger-ui .authorization__btn svg { fill: #6d9eff !important; }
.swagger-ui .authorization__btn.locked svg { fill: #4ade80 !important; }

/* ── Auth modal ── */
.swagger-ui .dialog-ux .modal-ux {
    background: #18181b !important; border: 1px solid #27272a !important; border-radius: 12px !important;
}
.swagger-ui .dialog-ux .modal-ux-header { border-bottom: 1px solid #27272a !important; }
.swagger-ui .dialog-ux .modal-ux-header h3 { color: #fafafa !important; }
.swagger-ui .dialog-ux .modal-ux-content p,
.swagger-ui .dialog-ux .modal-ux-content label { color: #a1a1aa !important; }
.swagger-ui .dialog-ux .modal-ux-content input {
    background: #09090b !important; color: #e4e4e7 !important;
    border: 1px solid #27272a !important; border-radius: 6px !important;
    font-family: 'JetBrains Mono', monospace !important;
}
.swagger-ui .dialog-ux .backdrop-ux { background: rgba(0,0,0,0.75) !important; }
.swagger-ui .auth-btn-wrapper .btn { border-radius: 6px !important; }
.swagger-ui .auth-btn-wrapper .btn-done {
    background: #6d9eff !important; color: #09090b !important; border: none !important;
    font-weight: 600 !important;
}
.swagger-ui .auth-btn-wrapper .btn:not(.btn-done) { color: #a1a1aa !important; border-color: #3f3f46 !important; }

/* ── Scheme container ── */
.swagger-ui .scheme-container { border-bottom: 1px solid #1c1c20 !important; padding: 16px 0 !important; }
.swagger-ui .scheme-container select { background: #18181b !important; color: #e4e4e7 !important; border: 1px solid #27272a !important; }

/* ── Tag sections ── */
.swagger-ui .opblock-tag { color: #fafafa !important; border-bottom: 1px solid #1c1c20 !important; font-weight: 600 !important; }
.swagger-ui .opblock-tag small { color: #71717a !important; }
.swagger-ui .opblock-tag:hover { background: #111113 !important; }
.swagger-ui .opblock-tag svg { fill: #71717a !important; }

/* ── Endpoint cards ── */
.swagger-ui .opblock {
    border-radius: 8px !important; border: 1px solid #27272a !important;
    margin-bottom: 8px !important; overflow: hidden !important;
    box-shadow: 0 1px 3px rgba(0,0,0,0.4) !important;
}

/* GET — blue */
.swagger-ui .opblock.opblock-get { background: #0c1425 !important; border-color: #1e3a5f !important; }
.swagger-ui .opblock.opblock-get .opblock-summary-method {
    background: #6d9eff !important; color: #09090b !important;
    border-radius: 4px !important; font-weight: 700 !important; min-width: 60px !important; text-align: center !important;
}
.swagger-ui .opblock.opblock-get .opblock-summary { border-color: transparent !important; }

/* POST — green */
.swagger-ui .opblock.opblock-post { background: #0c1f14 !important; border-color: #1a4d2e !important; }
.swagger-ui .opblock.opblock-post .opblock-summary-method {
    background: #4ade80 !important; color: #09090b !important;
    border-radius: 4px !important; font-weight: 700 !important; min-width: 60px !important; text-align: center !important;
}
.swagger-ui .opblock.opblock-post .opblock-summary { border-color: transparent !important; }

/* PUT — orange */
.swagger-ui .opblock.opblock-put { background: #1a1508 !important; border-color: #4d3d1a !important; }
.swagger-ui .opblock.opblock-put .opblock-summary-method {
    background: #fb923c !important; color: #09090b !important;
    border-radius: 4px !important; font-weight: 700 !important; min-width: 60px !important; text-align: center !important;
}

/* DELETE — red */
.swagger-ui .opblock.opblock-delete { background: #1a0c0c !important; border-color: #4d1a1a !important; }
.swagger-ui .opblock.opblock-delete .opblock-summary-method {
    background: #f87171 !important; color: #09090b !important;
    border-radius: 4px !important; font-weight: 700 !important; min-width: 60px !important; text-align: center !important;
}

/* Endpoint path and description */
.swagger-ui .opblock .opblock-summary-path { color: #e4e4e7 !important; }
.swagger-ui .opblock .opblock-summary-path span { color: #e4e4e7 !important; }
.swagger-ui .opblock .opblock-summary-description { color: #71717a !important; }

/* ── Expanded endpoint body ── */
.swagger-ui .opblock .opblock-body,
.swagger-ui .opblock .opblock-section-header {
    background: #0e0e12 !important; border-color: #27272a !important;
}
.swagger-ui .opblock .opblock-section-header h4 { color: #d4d4d8 !important; }
.swagger-ui .opblock .opblock-section-header label { color: #71717a !important; }
.swagger-ui .opblock .opblock-section-header label span { color: #71717a !important; }

/* ── Parameters ── */
.swagger-ui .parameters-col_description,
.swagger-ui .parameters-col_name { color: #a1a1aa !important; }
.swagger-ui .parameter__name { color: #e4e4e7 !important; }
.swagger-ui .parameter__name.required::after { color: #f87171 !important; }
.swagger-ui .parameter__type { color: #6d9eff !important; }
.swagger-ui .parameter__in { color: #71717a !important; }
.swagger-ui table thead tr th { color: #71717a !important; border-color: #27272a !important; background: transparent !important; }
.swagger-ui table thead tr td,
.swagger-ui table tbody tr td { color: #a1a1aa !important; border-color: #27272a !important; background: transparent !important; }

/* ── Parameter inputs ── */
.swagger-ui input[type=text],
.swagger-ui input[type=search],
.swagger-ui input[type=email],
.swagger-ui input[type=file],
.swagger-ui input[type=password],
.swagger-ui input[type=number],
.swagger-ui textarea,
.swagger-ui select {
    background: #09090b !important; color: #e4e4e7 !important;
    border: 1px solid #3f3f46 !important; border-radius: 6px !important;
    padding: 6px 10px !important;
}
.swagger-ui select option { background: #18181b !important; color: #e4e4e7 !important; }
.swagger-ui .body-param__text { background: #09090b !important; color: #e4e4e7 !important; }

/* ── Response section ── */
.swagger-ui .responses-wrapper,
.swagger-ui .responses-inner { background: transparent !important; }
.swagger-ui .response-col_status { color: #6d9eff !important; font-weight: 600 !important; }
.swagger-ui .response-col_description { color: #a1a1aa !important; }
.swagger-ui .response-col_description__inner p { color: #a1a1aa !important; }
.swagger-ui .response-col_links { color: #71717a !important; }
.swagger-ui .responses-table { background: transparent !important; }

/* Live response */
.swagger-ui .live-responses-table .response > td { border-color: #27272a !important; }
.swagger-ui .live-responses-table .response-col_status { color: #4ade80 !important; }
.swagger-ui .responses-header td { color: #a1a1aa !important; }
.swagger-ui .response-controls { background: transparent !important; }

/* Response content type dropdown */
.swagger-ui .responses-controls { background: transparent !important; }
.swagger-ui .response-control-media-type__accept-message { color: #4ade80 !important; }

/* ── Code blocks ── */
.swagger-ui .highlight-code,
.swagger-ui .microlight,
.swagger-ui code,
.swagger-ui pre {
    font-family: 'JetBrains Mono', 'Fira Code', monospace !important;
    background: #111113 !important; color: #d4d4d8 !important;
    border-radius: 6px !important; font-size: 13px !important;
}
.swagger-ui .microlight { padding: 12px !important; line-height: 1.5 !important; }
/* Syntax highlighting in response */
.swagger-ui .microlight .headerline { color: #71717a !important; }

/* Curl command box */
.swagger-ui .curl-command .copy-to-clipboard { background: #18181b !important; border: 1px solid #27272a !important; border-radius: 4px !important; }
.swagger-ui .curl-command .copy-to-clipboard button { background: transparent !important; color: #a1a1aa !important; }

/* ── Model / Schema ── */
.swagger-ui section.models { border: 1px solid #27272a !important; border-radius: 8px !important; }
.swagger-ui section.models h4 { color: #fafafa !important; border-color: #27272a !important; }
.swagger-ui section.models h4 svg { fill: #71717a !important; }
.swagger-ui .model-box { background: #111113 !important; border-radius: 6px !important; }
.swagger-ui .model { color: #a1a1aa !important; }
.swagger-ui .model-title { color: #fafafa !important; }
.swagger-ui .model-title__text { color: #fafafa !important; }
.swagger-ui .prop-type { color: #6d9eff !important; }
.swagger-ui .prop-format { color: #71717a !important; }
.swagger-ui .model .property { color: #a1a1aa !important; }
.swagger-ui .model span.prop-enum { color: #fb923c !important; }
.swagger-ui .model-toggle::after { background: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><path d="M0 3 L5 8 L10 3" fill="none" stroke="%2371717a" stroke-width="2"/></svg>') center no-repeat !important; }

/* ── Buttons ── */
.swagger-ui .btn.try-out__btn {
    border: 1px solid #6d9eff !important; color: #6d9eff !important;
    border-radius: 6px !important; background: transparent !important;
}
.swagger-ui .btn.try-out__btn:hover { background: #6d9eff !important; color: #09090b !important; }

.swagger-ui .btn.execute {
    background: #6d9eff !important; color: #09090b !important;
    border: none !important; border-radius: 6px !important; font-weight: 600 !important;
}
.swagger-ui .btn.execute:hover { background: #93b4ff !important; }

.swagger-ui .btn.btn-clear,
.swagger-ui .btn.cancel {
    border: 1px solid #3f3f46 !important; color: #a1a1aa !important;
    border-radius: 6px !important; background: transparent !important;
}

/* Download buttons */
.swagger-ui .download-contents { background: #18181b !important; color: #a1a1aa !important; border: 1px solid #27272a !important; border-radius: 4px !important; }

/* ── Miscellaneous ── */
.swagger-ui .opblock-summary .authorization__btn { opacity: 0.7 !important; }
.swagger-ui .loading-container .loading:after { color: #6d9eff !important; }
.swagger-ui .arrow { fill: #71717a !important; }
.swagger-ui svg.arrow { fill: #71717a !important; }
.swagger-ui .expand-operation svg { fill: #71717a !important; }
.swagger-ui .renderedMarkdown p { color: #a1a1aa !important; }

/* Filter/search box */
.swagger-ui .filter-container { background: #09090b !important; }
.swagger-ui .filter-container .operation-filter-input {
    background: #18181b !important; color: #e4e4e7 !important; border: 1px solid #27272a !important;
}

/* Servers dropdown */
.swagger-ui .servers > label { color: #a1a1aa !important; }
.swagger-ui .servers > label select { background: #18181b !important; color: #e4e4e7 !important; border: 1px solid #27272a !important; }

/* ── Scrollbar ── */
.swagger-ui ::-webkit-scrollbar { width: 6px; height: 6px; }
.swagger-ui ::-webkit-scrollbar-track { background: #09090b; }
.swagger-ui ::-webkit-scrollbar-thumb { background: #3f3f46; border-radius: 3px; }
.swagger-ui ::-webkit-scrollbar-thumb:hover { background: #52525b; }

/* ── Version badge ── */
.swagger-ui .info .title small { background: #18181b !important; color: #6d9eff !important; border-radius: 4px !important; padding: 2px 8px !important; }
.swagger-ui .info .title small.version-stamp { background: #18181b !important; }
.swagger-ui .info .title small pre { background: transparent !important; color: #6d9eff !important; }

/* Links */
.swagger-ui a { color: #6d9eff !important; }
.swagger-ui a:hover { color: #93b4ff !important; }
"""

app = FastAPI(
    title="QuantumRand API",
    description=API_DESCRIPTION,
    version=API_VERSION,
    docs_url=None,
    redoc_url=None,
    lifespan=lifespan,
)


def custom_openapi():
    """Remove 422 Validation Error from all endpoint docs."""
    if app.openapi_schema:
        return app.openapi_schema
    from fastapi.openapi.utils import get_openapi
    schema = get_openapi(
        title=app.title, version=app.version,
        description=app.description, routes=app.routes,
    )
    for path in schema.get("paths", {}).values():
        for method in path.values():
            method.get("responses", {}).pop("422", None)
    # Remove ValidationError schema if unused
    schema.get("components", {}).get("schemas", {}).pop("ValidationError", None)
    schema.get("components", {}).get("schemas", {}).pop("HTTPValidationError", None)
    app.openapi_schema = schema
    return schema

app.openapi = custom_openapi

# CORS
origins = ALLOWED_ORIGINS if isinstance(ALLOWED_ORIGINS, list) else ALLOWED_ORIGINS.split(",")
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

engine = QuantumEngine()

# Initialize entropy pool
from app.cache import init_pool, start_pool, pool_stats
init_pool(engine)

# V1 API router — all versioned endpoints available at both /path and /v1/path
v1 = APIRouter(prefix="/v1", include_in_schema=False)

# Mount static files
static_dir = Path(__file__).parent / "static"
if static_dir.exists():
    app.mount("/static", StaticFiles(directory=str(static_dir)), name="static")


# --- Custom docs route ---

@app.get("/docs", include_in_schema=False)
async def custom_swagger_ui():
    openapi_url = app.openapi_url or "/openapi.json"
    return HTMLResponse(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QuantumRand API Docs</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>Q</text></svg>">
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>{CUSTOM_CSS}</style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
    <script>
        SwaggerUIBundle({{
            url: "{openapi_url}",
            dom_id: '#swagger-ui',
            presets: [SwaggerUIBundle.presets.apis, SwaggerUIBundle.SwaggerUIStandalonePreset],
            layout: "BaseLayout",
            deepLinking: true,
            defaultModelsExpandDepth: -1,
            docExpansion: "list",
            persistAuthorization: true,
        }});
    </script>
</body>
</html>""")


# --- Middleware ---

@app.middleware("http")
async def request_logging(request: Request, call_next):
    # Request ID — echo client's or generate one
    request_id = request.headers.get("x-request-id") or uuid.uuid4().hex
    request.state.request_id = request_id

    start = time.perf_counter()
    response = await call_next(request)
    elapsed_ms = round((time.perf_counter() - start) * 1000, 2)
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    logger.info(f"{timestamp} | {request.method} | {request.url.path} | {response.status_code} | {elapsed_ms}ms | {request_id}")

    # Always include request ID
    response.headers["X-Request-ID"] = request_id

    # Inject rate limit headers if available
    rl = get_ratelimit_info()
    if rl:
        response.headers["X-RateLimit-Limit"] = str(rl["limit"])
        response.headers["X-RateLimit-Remaining"] = str(rl["remaining"])
        response.headers["X-RateLimit-Used"] = str(rl["used"])
        from datetime import datetime, timezone, timedelta
        _now = datetime.now(timezone.utc)
        _midnight = (_now + timedelta(days=1)).replace(hour=0, minute=0, second=0, microsecond=0)
        response.headers["X-RateLimit-Reset"] = str(int((_midnight - _now).total_seconds()))
        if rl.get("warning"):
            response.headers["X-RateLimit-Warning"] = rl["warning"]

    return response


# --- Global exception handler ---

@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request: Request, exc: StarletteHTTPException):
    request_id = getattr(request.state, "request_id", None) or uuid.uuid4().hex
    headers = {"X-Request-ID": request_id}
    if getattr(exc, "headers", None):
        headers.update(exc.headers)
    return JSONResponse(
        status_code=exc.status_code,
        content={"success": False, "error": exc.detail, "request_id": request_id},
        headers=headers,
    )


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    request_id = getattr(request.state, "request_id", None) or uuid.uuid4().hex
    errors = exc.errors()
    # Build a human-friendly message from the first error
    if errors:
        e = errors[0]
        field = ".".join(str(loc) for loc in e.get("loc", []) if loc != "query")
        msg = e.get("msg", "Invalid input")
        detail = f"{field}: {msg}" if field else msg
    else:
        detail = "Invalid request parameters"
    return JSONResponse(
        status_code=422,
        content={"success": False, "error": detail, "request_id": request_id},
        headers={"X-Request-ID": request_id},
    )


@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    request_id = getattr(request.state, "request_id", None) or uuid.uuid4().hex
    logger.error(f"Unhandled exception ({request_id}): {exc}")
    return JSONResponse(
        status_code=500,
        content={"success": False, "error": "Internal server error", "request_id": request_id},
        headers={"X-Request-ID": request_id},
    )


class KeyCreateRequest(BaseModel):
    name: str
    email: str
    tier: str = "free"


class BatchRequest(BaseModel):
    requests: list[dict]


class WebhookRequest(BaseModel):
    callback_url: str
    type: str = "bits"
    params: dict = {}


class AllowedIpsRequest(BaseModel):
    ips: list[str]


# --- Public endpoints ---

@app.get("/", response_class=HTMLResponse, summary="Landing Page",
         description="Serves the QuantumRand landing page.")
def landing_page():
    index_path = Path(__file__).parent / "static" / "index.html"
    if index_path.exists():
        return HTMLResponse(content=index_path.read_text())
    return HTMLResponse(content=f"<h1>{APP_NAME}</h1>")


@app.get("/terms", response_class=HTMLResponse, include_in_schema=False)
def terms_page():
    path = Path(__file__).parent / "static" / "terms.html"
    if path.exists():
        return HTMLResponse(content=path.read_text())
    raise HTTPException(status_code=404, detail="Not found")


@app.get("/privacy", response_class=HTMLResponse, include_in_schema=False)
def privacy_page():
    path = Path(__file__).parent / "static" / "privacy.html"
    if path.exists():
        return HTMLResponse(content=path.read_text())
    raise HTTPException(status_code=404, detail="Not found")


@app.get("/demo/bits", include_in_schema=False)
def demo_bits(request: Request):
    """Unauthenticated demo endpoint for landing page (64 bits only, rate limited)."""
    client_ip = request.client.host if request.client else "unknown"
    if not _check_demo_rate(client_ip):
        raise HTTPException(status_code=429, detail="Demo rate limit exceeded. Try again in a minute.")
    try:
        result = engine.generate_bits(64, "origin_cloud")
        return {"success": True, "data": result}
    except Exception:
        result = engine.generate_bits(64, "aer_simulator")
        return {"success": True, "data": result}


@app.get("/api/info", summary="API Info",
         description="API version and status info. Returns available endpoints, version, and environment.")
def api_info():
    return {
        "success": True,
        "data": {
            "name": "QuantumRand API",
            "version": API_VERSION,
            "description": "Quantum Random Number Generator powered by Qiskit AerSimulator",
            "environment": ENV,
            "endpoints": [
                "GET  /              - Landing page",
                "GET  /api/info      - API info (public)",
                "GET  /health        - Health check (public)",
                "GET  /generate/bits - Generate random bits (auth required)",
                "GET  /generate/hex  - Generate random hex string (auth required)",
                "GET  /generate/integer - Generate random integer (auth required)",
                "POST /generate/key  - Generate cryptographic key (auth required)",
                "POST /generate/batch - Batch generate multiple values (auth required)",
                "POST /generate/webhook - Async generation with webhook delivery (auth required)",
                "POST /keys/create   - Create new API key (public)",
                "GET  /keys/me       - Get your key info (auth required)",
                "GET  /keys/stats    - Get usage stats (auth required)",
                "POST /keys/revoke   - Revoke your API key (auth required)",
            ],
        },
    }


@app.get("/health", summary="Health Check",
         description="System health check for all components. Returns status of database, quantum engine, uptime, and environment.")
def health():
    _health_start = time.time()
    uptime_seconds = round(_health_start - START_TIME, 2)
    try:
        db_ok = check_connection()
    except Exception:
        db_ok = False
    engine_result = engine.health_check()
    engine_ok = engine_result.get("status") == "healthy"
    overall = "healthy" if (db_ok and engine_ok) else "unhealthy"
    status_code = 200 if overall == "healthy" else 503

    try:
        import resource as _resource
        import platform as _platform
        _rss = _resource.getrusage(_resource.RUSAGE_SELF).ru_maxrss
        # macOS ru_maxrss is in bytes; Linux is in kilobytes
        memory_mb = round(_rss / 1024 / 1024 if _platform.system() == "Darwin" else _rss / 1024, 2)
    except Exception:
        memory_mb = None

    response_time_ms = round((time.time() - _health_start) * 1000, 2)

    return JSONResponse(
        status_code=status_code,
        content={
            "success": overall == "healthy",
            "data": {
                "status": overall,
                "environment": ENV,
                "version": API_VERSION,
                "uptime_seconds": uptime_seconds,
                "database": "connected" if db_ok else "disconnected",
                "quantum_engine": "healthy" if engine_ok else "unhealthy",
                "entropy_pool": pool_stats(),
                "memory_mb": memory_mb,
                "response_time_ms": response_time_ms,
            },
        },
    )


@app.get("/backends", summary="List Backends",
         description="List all available quantum backends and their status. Includes local simulator and Origin Quantum cloud/hardware options.")
def list_backends():
    return {
        "success": True,
        "data": {
            "backends": engine._available_backends(),
            "default": "aer_simulator",
        },
    }


# --- Key management endpoints ---

@app.post("/keys/create", summary="Create API Key",
          description="Create a free API key instantly. Provide a name, email, and optional tier (free/indie/startup/business).")
def keys_create(body: KeyCreateRequest):
    try:
        result = create_api_key(body.name, body.email, body.tier)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    return {"success": True, "data": result}


@app.get("/keys/me", summary="My Key Info",
         description="View your key details and tier. Returns name, email, tier, active status, creation date, and rate limits.")
def keys_me(key_record: dict = Depends(require_api_key)):
    return {
        "success": True,
        "data": {
            "name": key_record["name"],
            "email": key_record["email"],
            "tier": key_record["tier"],
            "is_active": bool(key_record["is_active"]),
            "created_at": key_record["created_at"],
            "last_used_at": key_record["last_used_at"],
            "rate_limit": TIER_LIMITS[key_record["tier"]],
        },
    }


@app.post("/keys/rotate", summary="Rotate API Key",
          description="Generate a new API key and deactivate the old one. Usage history is transferred to the new key.")
def keys_rotate(key_record: dict = Depends(require_api_key)):
    result = rotate_api_key(key_record["key"])
    if not result:
        raise HTTPException(status_code=404, detail="Key not found")
    return {"success": True, "data": result}


@app.post("/keys/revoke", summary="Revoke API Key",
          description="Deactivate your API key. It will no longer be accepted for requests. This action can be undone by an admin.")
def keys_revoke(key_record: dict = Depends(require_api_key)):
    deactivate_api_key(key_record["key"])
    return {"success": True, "data": {"message": "API key revoked", "key": key_record["key"]}}


@app.get("/keys/stats", summary="Usage Statistics",
         description="View your usage statistics. Returns total calls, total bits generated, calls today, and calls this month.")
def keys_stats(key_record: dict = Depends(require_api_key)):
    stats = get_usage_stats(key_record["key"])
    stats["tier"] = key_record["tier"]
    stats["rate_limit"] = TIER_LIMITS[key_record["tier"]]
    return {"success": True, "data": stats}


@app.get("/keys/export", summary="Export Usage Data",
         description="Download your usage history as a CSV file. Includes timestamp, endpoint, bits requested, and latency for every call.")
def keys_export(key_record: dict = Depends(require_api_key)):
    import io
    import csv
    logs = get_usage_logs(key_record["key"])
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["timestamp", "endpoint", "bits_requested", "elapsed_ms"])
    for log in logs:
        writer.writerow([
            log.get("timestamp", ""),
            log.get("endpoint", ""),
            log.get("bits_requested", 0),
            log.get("elapsed_ms", 0),
        ])
    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="text/csv",
        headers={"Content-Disposition": "attachment; filename=quantumrand_usage.csv"},
    )


@app.get("/keys/allowed-ips", summary="View IP Allowlist",
         description="View the IP addresses allowed to use your API key. Empty list means no restriction.")
def keys_get_allowed_ips(key_record: dict = Depends(require_api_key)):
    return {"success": True, "data": {"allowed_ips": key_record.get("allowed_ips", [])}}


@app.post("/keys/allowed-ips", summary="Update IP Allowlist",
          description="Set the IP addresses allowed to use your API key. Send empty list to remove restriction. Your current IP must be in the list.")
def keys_set_allowed_ips(request: Request, body: AllowedIpsRequest, key_record: dict = Depends(require_api_key)):
    from app.auth import _get_client_ip
    if body.ips:
        current_ip = _get_client_ip(request)
        if current_ip not in body.ips:
            raise HTTPException(status_code=400, detail=f"Your current IP ({current_ip}) must be in the allowlist to avoid locking yourself out.")
    try:
        update_allowed_ips(key_record["key"], body.ips)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    return {"success": True, "data": {"allowed_ips": body.ips, "message": "IP allowlist updated"}}


@app.post("/keys/signing/enable", summary="Enable Request Signing",
          description="Enable HMAC-SHA256 request signing for your API key. Returns the signing secret (shown only once). All future requests must include X-Signature and X-Timestamp headers.")
def keys_enable_signing(key_record: dict = Depends(require_api_key)):
    secret = enable_signing(key_record["key"])
    if not secret:
        raise HTTPException(status_code=404, detail="Key not found")
    return {
        "success": True,
        "data": {
            "hmac_secret": secret,
            "message": "Signing enabled. Save this secret — it will not be shown again.",
            "usage": "X-Signature = HMAC-SHA256(secret, timestamp + method + path + query), X-Timestamp = Unix epoch",
        },
    }


@app.post("/keys/signing/disable", summary="Disable Request Signing",
          description="Disable HMAC-SHA256 request signing for your API key.")
def keys_disable_signing(key_record: dict = Depends(require_api_key)):
    disable_signing(key_record["key"])
    return {"success": True, "data": {"message": "Request signing disabled"}}


# --- Admin endpoints ---

@app.get("/admin/{secret}/keys", summary="List All API Keys (Admin)",
         description="Admin-only: list all API keys.",
         include_in_schema=False)
def admin_list_keys(secret: str):
    _require_admin(secret)
    keys = list_all_keys()
    return {"success": True, "data": {"total": len(keys), "keys": keys}}


@app.get("/admin/{secret}/dashboard", include_in_schema=False)
def admin_dashboard(secret: str):
    _require_admin(secret)
    dashboard_path = Path(__file__).parent / "static" / "dashboard.html"
    if not dashboard_path.exists():
        raise HTTPException(status_code=500, detail="Dashboard template not found")
    html = dashboard_path.read_text().replace("{{ADMIN_SECRET}}", secret)
    return HTMLResponse(content=html)


@app.get("/admin/{secret}/dashboard/data", include_in_schema=False)
def admin_dashboard_data(secret: str):
    _require_admin(secret)
    return {"success": True, "data": get_dashboard_stats()}


@app.post("/admin/{secret}/keys/{key}/reactivate", include_in_schema=False)
def admin_reactivate_key(secret: str, key: str):
    _require_admin(secret)
    if not reactivate_api_key(key):
        raise HTTPException(status_code=404, detail="Key not found")
    return {"success": True, "data": {"message": "API key reactivated", "key": key}}


@app.post("/admin/{secret}/keys/{key}/deactivate", include_in_schema=False)
def admin_deactivate_key(secret: str, key: str):
    _require_admin(secret)
    if not deactivate_api_key(key):
        raise HTTPException(status_code=404, detail="Key not found")
    return {"success": True, "data": {"message": "API key deactivated", "key": key}}


class TierUpdateRequest(BaseModel):
    tier: str


@app.post("/admin/{secret}/keys/{key}/tier", include_in_schema=False)
def admin_update_tier(secret: str, key: str, body: TierUpdateRequest):
    _require_admin(secret)
    try:
        if not update_api_key_tier(key, body.tier):
            raise HTTPException(status_code=404, detail="Key not found")
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    return {"success": True, "data": {"message": f"Tier updated to {body.tier}", "key": key}}


@app.post("/admin/{secret}/migrate-keys", include_in_schema=False)
def admin_migrate_keys(secret: str):
    """One-time migration: hash all legacy plaintext API key document IDs."""
    _require_admin(secret)
    count = migrate_plaintext_keys()
    return {"success": True, "data": {"migrated": count, "message": f"Migrated {count} keys to hashed storage"}}


# --- Authenticated generate endpoints ---

def _log_and_update(api_key: str, endpoint: str, bits: int, elapsed_ms: float):
    log_usage(api_key, endpoint, bits, elapsed_ms)
    update_last_used(api_key)


@app.get("/generate/bits", summary="Generate Random Bits",
         description="Generate raw quantum random bits. Specify count with `n` (1-4096). Optionally choose a `backend` (aer_simulator, origin_cloud, origin_wuyuan).")
def generate_bits(
    n: int = Query(default=256, ge=1, le=4096),
    backend: str = Query(default="origin_cloud", description="Quantum backend to use"),
    key_record: dict = Depends(require_api_key),
):
    if backend not in VALID_BACKENDS:
        raise HTTPException(status_code=400, detail=f"Invalid backend. Choose from: {VALID_BACKENDS}")
    max_bits = TIER_LIMITS[key_record["tier"]]["max_bits"]
    if n > max_bits:
        raise HTTPException(
            status_code=400,
            detail=f"Your '{key_record['tier']}' tier allows max {max_bits} bits per call.",
        )
    try:
        result = engine.generate_bits(n, backend)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except RuntimeError as e:
        logger.error(f"generate_bits failed: {e}")
        raise HTTPException(status_code=502, detail="Quantum backend unavailable. Try aer_simulator or retry later.")
    _log_and_update(key_record["key"], "/generate/bits", n, result["elapsed_ms"])
    return {"success": True, "data": result}


@app.get("/generate/hex", summary="Generate Random Hex",
         description="Generate a quantum random hex string. `n` must be a multiple of 4 (4-4096). Optionally choose a `backend`.")
def generate_hex(
    n: int = Query(default=256, ge=4, le=4096),
    backend: str = Query(default="origin_cloud", description="Quantum backend to use"),
    key_record: dict = Depends(require_api_key),
):
    if backend not in VALID_BACKENDS:
        raise HTTPException(status_code=400, detail=f"Invalid backend. Choose from: {VALID_BACKENDS}")
    if n % 4 != 0:
        raise HTTPException(status_code=400, detail="n must be a multiple of 4")
    max_bits = TIER_LIMITS[key_record["tier"]]["max_bits"]
    if n > max_bits:
        raise HTTPException(
            status_code=400,
            detail=f"Your '{key_record['tier']}' tier allows max {max_bits} bits per call.",
        )
    try:
        result = engine.generate_bits(n, backend)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except RuntimeError as e:
        logger.error(f"generate_hex failed: {e}")
        raise HTTPException(status_code=502, detail="Quantum backend unavailable. Try aer_simulator or retry later.")
    _log_and_update(key_record["key"], "/generate/hex", n, result["elapsed_ms"])
    return {
        "success": True,
        "data": {
            "hex": result["hex"],
            "num_bits": n,
            "elapsed_ms": result["elapsed_ms"],
            "source": result["source"],
        },
    }


@app.get("/generate/integer", summary="Generate Random Integer",
         description="Generate a quantum random integer in a given range. Uses rejection sampling for uniform distribution. Optionally choose a `backend`.")
def generate_integer(
    min: int = Query(default=0, ge=-(2**31), le=2**31 - 1),
    max: int = Query(default=100, ge=-(2**31), le=2**31 - 1),
    backend: str = Query(default="origin_cloud", description="Quantum backend to use"),
    key_record: dict = Depends(require_api_key),
):
    if backend not in VALID_BACKENDS:
        raise HTTPException(status_code=400, detail=f"Invalid backend. Choose from: {VALID_BACKENDS}")
    if min >= max:
        raise HTTPException(status_code=400, detail="min must be less than max")
    if max - min > 2**20:
        raise HTTPException(status_code=400, detail="Range too large. Maximum range is 2^20 (1,048,576).")
    try:
        result = engine.generate_integer(min, max, backend)
    except (ValueError, RuntimeError):
        raise HTTPException(status_code=400, detail="Failed to generate integer. Try a smaller range.")
    _log_and_update(key_record["key"], "/generate/integer", result["bits_used"], result["elapsed_ms"])
    return {"success": True, "data": result}


@app.post("/generate/key", summary="Generate Cryptographic Key",
          description="Generate a cryptographic key using quantum randomness. Supports 128, 192, 256, or 512 bit keys. Optionally choose a `backend`.")
def generate_key(
    bits: int = Query(default=256, description="Key size: 128, 192, 256, or 512"),
    backend: str = Query(default="origin_cloud", description="Quantum backend to use"),
    key_record: dict = Depends(require_api_key),
):
    if backend not in VALID_BACKENDS:
        raise HTTPException(status_code=400, detail=f"Invalid backend. Choose from: {VALID_BACKENDS}")
    max_bits = TIER_LIMITS[key_record["tier"]]["max_bits"]
    if bits > max_bits:
        raise HTTPException(
            status_code=400,
            detail=f"Your '{key_record['tier']}' tier allows max {max_bits} bits per call.",
        )
    try:
        result = engine.generate_key(bits, backend)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except RuntimeError as e:
        logger.error(f"generate_key failed: {e}")
        raise HTTPException(status_code=502, detail="Quantum backend unavailable. Try aer_simulator or retry later.")
    _log_and_update(key_record["key"], "/generate/key", bits, result["elapsed_ms"])
    return {"success": True, "data": result}


@app.post("/generate/batch", summary="Batch Generate",
          description="Generate multiple random values in one call. Send a list of requests, each with a `type` (bits/hex/integer/key) and `params`.")
def generate_batch(
    body: BatchRequest,
    backend: str = Query(default="origin_cloud", description="Quantum backend to use"),
    key_record: dict = Depends(require_api_key),
):
    if len(body.requests) > 20:
        raise HTTPException(status_code=400, detail="Maximum 20 requests per batch")
    if len(body.requests) == 0:
        raise HTTPException(status_code=400, detail="At least one request required")
    if backend not in VALID_BACKENDS:
        raise HTTPException(status_code=400, detail=f"Invalid backend. Choose from: {VALID_BACKENDS}")

    max_bits = TIER_LIMITS[key_record["tier"]]["max_bits"]
    results = []
    total_bits = 0
    total_elapsed = 0

    for i, req in enumerate(body.requests):
        req_type = req.get("type", "bits")
        params = req.get("params", {})
        try:
            if req_type == "bits":
                n = int(params.get("n", 256))
                if n > max_bits:
                    raise ValueError(f"Max {max_bits} bits for your tier")
                r = engine.generate_bits(n, backend)
                total_bits += n
                total_elapsed += r["elapsed_ms"]
                results.append({"index": i, "type": "bits", "data": r})
            elif req_type == "hex":
                n = int(params.get("n", 256))
                if n > max_bits:
                    raise ValueError(f"Max {max_bits} bits for your tier")
                r = engine.generate_bits(n, backend)
                total_bits += n
                total_elapsed += r["elapsed_ms"]
                results.append({"index": i, "type": "hex", "data": {"hex": r["hex"], "num_bits": n, "source": backend}})
            elif req_type == "integer":
                min_val = int(params.get("min", 0))
                max_val = int(params.get("max", 100))
                r = engine.generate_integer(min_val, max_val, backend)
                total_bits += r["bits_used"]
                total_elapsed += r["elapsed_ms"]
                results.append({"index": i, "type": "integer", "data": r})
            elif req_type == "key":
                bits = int(params.get("bits", 256))
                if bits > max_bits:
                    raise ValueError(f"Max {max_bits} bits for your tier")
                r = engine.generate_key(bits, backend)
                total_bits += bits
                total_elapsed += r["elapsed_ms"]
                results.append({"index": i, "type": "key", "data": r})
            else:
                results.append({"index": i, "type": req_type, "error": f"Unknown type: {req_type}"})
        except ValueError as e:
            results.append({"index": i, "type": req_type, "error": str(e)})
        except RuntimeError:
            results.append({"index": i, "type": req_type, "error": "Quantum backend unavailable"})
        except Exception:
            results.append({"index": i, "type": req_type, "error": "Unexpected error processing request"})

    _log_and_update(key_record["key"], "/generate/batch", total_bits, total_elapsed)
    return {
        "success": True,
        "data": {
            "count": len(results),
            "total_bits": total_bits,
            "total_elapsed_ms": round(total_elapsed, 2),
            "results": results,
        },
    }


@app.post("/generate/webhook", summary="Webhook Generate",
          description="Generate quantum randomness and deliver results to a callback URL. Returns immediately with a job ID. Results are POSTed to your URL when ready.")
def generate_webhook(
    body: WebhookRequest,
    backend: str = Query(default="origin_cloud", description="Quantum backend to use"),
    key_record: dict = Depends(require_api_key),
):
    if backend not in VALID_BACKENDS:
        raise HTTPException(status_code=400, detail=f"Invalid backend. Choose from: {VALID_BACKENDS}")
    _validate_webhook_url(body.callback_url)

    import uuid
    job_id = f"wh_{uuid.uuid4().hex[:16]}"

    import threading

    def _webhook_worker():
        try:
            max_bits = TIER_LIMITS[key_record["tier"]]["max_bits"]
            params = body.params
            if body.type == "bits":
                n = int(params.get("n", 256))
                n = min(n, max_bits)
                result = engine.generate_bits(n, backend)
                payload = {"job_id": job_id, "type": "bits", "data": result}
            elif body.type == "hex":
                n = int(params.get("n", 256))
                n = min(n, max_bits)
                result = engine.generate_bits(n, backend)
                payload = {"job_id": job_id, "type": "hex", "data": {"hex": result["hex"], "num_bits": n}}
            elif body.type == "integer":
                min_val = int(params.get("min", 0))
                max_val = int(params.get("max", 100))
                result = engine.generate_integer(min_val, max_val, backend)
                payload = {"job_id": job_id, "type": "integer", "data": result}
            elif body.type == "key":
                bits = int(params.get("bits", 256))
                bits = min(bits, max_bits)
                result = engine.generate_key(bits, backend)
                payload = {"job_id": job_id, "type": "key", "data": result}
            else:
                payload = {"job_id": job_id, "error": f"Unknown type: {body.type}"}

            import httpx
            httpx.post(body.callback_url, json=payload, timeout=10)
            _log_and_update(key_record["key"], "/generate/webhook", int(params.get("n", params.get("bits", 256))), 0)
        except Exception as e:
            logger.error(f"Webhook delivery failed for {job_id}: {e}")

    threading.Thread(target=_webhook_worker, daemon=True).start()

    return {
        "success": True,
        "data": {
            "job_id": job_id,
            "callback_url": body.callback_url,
            "type": body.type,
            "status": "processing",
            "message": "Results will be POSTed to your callback URL",
        },
    }


# --- V1 Router: mirror all API endpoints under /v1/ prefix ---
v1.add_api_route("/api/info", api_info, methods=["GET"])
v1.add_api_route("/backends", list_backends, methods=["GET"])
v1.add_api_route("/keys/create", keys_create, methods=["POST"])
v1.add_api_route("/keys/me", keys_me, methods=["GET"])
v1.add_api_route("/keys/rotate", keys_rotate, methods=["POST"])
v1.add_api_route("/keys/revoke", keys_revoke, methods=["POST"])
v1.add_api_route("/keys/stats", keys_stats, methods=["GET"])
v1.add_api_route("/keys/export", keys_export, methods=["GET"])
v1.add_api_route("/keys/allowed-ips", keys_get_allowed_ips, methods=["GET"])
v1.add_api_route("/keys/allowed-ips", keys_set_allowed_ips, methods=["POST"])
v1.add_api_route("/keys/signing/enable", keys_enable_signing, methods=["POST"])
v1.add_api_route("/keys/signing/disable", keys_disable_signing, methods=["POST"])
v1.add_api_route("/generate/bits", generate_bits, methods=["GET"])
v1.add_api_route("/generate/hex", generate_hex, methods=["GET"])
v1.add_api_route("/generate/integer", generate_integer, methods=["GET"])
v1.add_api_route("/generate/key", generate_key, methods=["POST"])
v1.add_api_route("/generate/batch", generate_batch, methods=["POST"])
v1.add_api_route("/generate/webhook", generate_webhook, methods=["POST"])
app.include_router(v1)
