import time
import logging
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, Query, HTTPException, Depends, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from app.config import ENV, API_VERSION, APP_NAME, ALLOWED_ORIGINS, PILOTOS_ENABLED, PILOTOS_PORT, ADMIN_SECRET
from app.quantum_engine import QuantumEngine, VALID_BACKENDS
from app.auth import require_api_key, TIER_LIMITS
from app.database import (
    create_api_key,
    log_usage,
    update_last_used,
    get_usage_stats,
    check_connection,
    list_all_keys,
)

logger = logging.getLogger("quantumrand")
logging.basicConfig(level=logging.INFO, format="%(message)s")


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Start embedded quantum simulator on boot if Origin backend is enabled."""
    if PILOTOS_ENABLED:
        try:
            from simulator.launcher import start_simulator, stop_simulator
            start_simulator(port=PILOTOS_PORT)
            logger.info("Embedded quantum simulator started")
        except Exception as e:
            logger.warning(f"Could not start embedded simulator: {e}")
    yield
    if PILOTOS_ENABLED:
        try:
            from simulator.launcher import stop_simulator
            stop_simulator()
        except Exception:
            pass

START_TIME = time.time()

API_DESCRIPTION = """
## Welcome to QuantumRand API

True quantum randomness as a service. Every number generated by this API is decided by quantum physics — not mathematical formulas.

### Quick Start
1. Create a free API key via **POST /keys/create**
2. Click **Authorize** above and paste your key
3. Call any **/generate/** endpoint

### Authentication
All /generate/ endpoints require an API key in the header: `X-API-Key: qr_your_key_here`

### Tiers
| Tier | Price | Calls/Day | Max Bits |
|------|-------|-----------|----------|
| Free | $0 | 100 | 256 |
| Indie | $9/mo | 1,000 | 1,024 |
| Startup | $49/mo | 10,000 | 2,048 |
| Business | $299/mo | 100,000 | 4,096 |

### Backends
| Backend | Provider | Type | Max Qubits |
|---------|----------|------|------------|
| `aer_simulator` | Qiskit | Local simulator | 1024 |
| `origin_cloud` | Origin Quantum | Cloud simulator | 6 |
| `origin_wuyuan` | Origin Quantum | Real quantum chip | 6 |

Pass `?backend=origin_wuyuan` to any /generate/ endpoint to use real quantum hardware.

### How It Works
Quantum bits are placed in superposition using Hadamard gates. When measured, physics — not math — decides the outcome. This produces randomness that is fundamentally unpredictable.
"""

CUSTOM_CSS = """
/* QuantumRand Dark Docs Theme */
html, body { background: #0a0a0a !important; }

.swagger-ui {
    font-family: 'Inter', -apple-system, sans-serif !important;
    color: #e0e0e0 !important;
}

/* Hide default topbar */
.swagger-ui .topbar { display: none !important; }

/* Dark background for everything */
.swagger-ui,
.swagger-ui .scheme-container,
.swagger-ui .info,
.swagger-ui .opblock-tag-section { background: #0a0a0a !important; }

/* Info section */
.swagger-ui .info .title { color: #4f8ef7 !important; font-size: 2em !important; }
.swagger-ui .info .description,
.swagger-ui .info .description p,
.swagger-ui .info .description li { color: #c0c0c0 !important; }
.swagger-ui .info .description h2,
.swagger-ui .info .description h3 { color: #ffffff !important; }
.swagger-ui .info .description code {
    background: #1a1a2e !important;
    color: #4f8ef7 !important;
    padding: 2px 6px !important;
    border-radius: 4px !important;
    font-family: 'JetBrains Mono', monospace !important;
}
.swagger-ui .info .description a { color: #4f8ef7 !important; }

/* Tables in description */
.swagger-ui .info .description table {
    border-collapse: collapse !important;
    width: 100% !important;
    margin: 16px 0 !important;
}
.swagger-ui .info .description th {
    background: #1a1a2e !important;
    color: #4f8ef7 !important;
    padding: 10px 14px !important;
    border: 1px solid #2a2a3e !important;
    text-align: left !important;
}
.swagger-ui .info .description td {
    background: #111118 !important;
    color: #c0c0c0 !important;
    padding: 8px 14px !important;
    border: 1px solid #2a2a3e !important;
}

/* Authorize button */
.swagger-ui .btn.authorize {
    background: #4f8ef7 !important;
    color: #fff !important;
    border: none !important;
    border-radius: 6px !important;
    font-weight: 600 !important;
    padding: 8px 20px !important;
    transition: background 0.2s !important;
}
.swagger-ui .btn.authorize:hover { background: #3a7ae0 !important; }
.swagger-ui .btn.authorize svg { fill: #fff !important; }
.swagger-ui .authorization__btn svg { fill: #4f8ef7 !important; }
.swagger-ui .authorization__btn.locked svg { fill: #22c55e !important; }

/* Auth modal */
.swagger-ui .dialog-ux .modal-ux {
    background: #111118 !important;
    border: 1px solid #2a2a3e !important;
    border-radius: 12px !important;
}
.swagger-ui .dialog-ux .modal-ux-header { border-bottom: 1px solid #2a2a3e !important; }
.swagger-ui .dialog-ux .modal-ux-header h3 { color: #fff !important; }
.swagger-ui .dialog-ux .modal-ux-content p,
.swagger-ui .dialog-ux .modal-ux-content label { color: #c0c0c0 !important; }
.swagger-ui .dialog-ux .modal-ux-content input {
    background: #0a0a0a !important;
    color: #e0e0e0 !important;
    border: 1px solid #2a2a3e !important;
    border-radius: 6px !important;
    font-family: 'JetBrains Mono', monospace !important;
}
.swagger-ui .dialog-ux .backdrop-ux { background: rgba(0,0,0,0.7) !important; }

/* Scheme container */
.swagger-ui .scheme-container {
    border-bottom: 1px solid #1a1a2e !important;
    padding: 16px 0 !important;
}

/* Tag sections */
.swagger-ui .opblock-tag {
    color: #ffffff !important;
    border-bottom: 1px solid #1a1a2e !important;
    font-weight: 600 !important;
}
.swagger-ui .opblock-tag small { color: #888 !important; }
.swagger-ui .opblock-tag:hover { background: #111118 !important; }

/* Endpoint cards */
.swagger-ui .opblock {
    border-radius: 8px !important;
    border: 1px solid #1e1e2e !important;
    margin-bottom: 8px !important;
    box-shadow: 0 2px 8px rgba(0,0,0,0.3) !important;
    overflow: hidden !important;
}

/* GET endpoints - quantum blue */
.swagger-ui .opblock.opblock-get {
    background: #0d1525 !important;
    border-color: #1a3a6e !important;
}
.swagger-ui .opblock.opblock-get .opblock-summary-method {
    background: #4f8ef7 !important;
    color: #fff !important;
    border-radius: 4px !important;
    font-weight: 700 !important;
    min-width: 60px !important;
    text-align: center !important;
}
.swagger-ui .opblock.opblock-get .opblock-summary {
    border-color: transparent !important;
}

/* POST endpoints - green */
.swagger-ui .opblock.opblock-post {
    background: #0d1f15 !important;
    border-color: #1a4e2e !important;
}
.swagger-ui .opblock.opblock-post .opblock-summary-method {
    background: #22c55e !important;
    color: #fff !important;
    border-radius: 4px !important;
    font-weight: 700 !important;
    min-width: 60px !important;
    text-align: center !important;
}
.swagger-ui .opblock.opblock-post .opblock-summary {
    border-color: transparent !important;
}

/* Endpoint path and description text */
.swagger-ui .opblock .opblock-summary-path { color: #e0e0e0 !important; }
.swagger-ui .opblock .opblock-summary-description { color: #999 !important; }

/* Expanded endpoint body */
.swagger-ui .opblock .opblock-body,
.swagger-ui .opblock .opblock-section-header {
    background: #0e0e16 !important;
    border-color: #1e1e2e !important;
}
.swagger-ui .opblock .opblock-section-header h4 { color: #ccc !important; }
.swagger-ui .opblock .opblock-section-header label { color: #999 !important; }

/* Parameters */
.swagger-ui .opblock .opblock-body .parameters-col_description,
.swagger-ui .opblock .opblock-body .parameters-col_name { color: #c0c0c0 !important; }
.swagger-ui table thead tr th { color: #999 !important; border-color: #1e1e2e !important; }
.swagger-ui table thead tr td { color: #c0c0c0 !important; border-color: #1e1e2e !important; }
.swagger-ui table tbody tr td { color: #c0c0c0 !important; border-color: #1e1e2e !important; }

/* Parameter inputs */
.swagger-ui input[type=text],
.swagger-ui textarea,
.swagger-ui select {
    background: #0a0a0a !important;
    color: #e0e0e0 !important;
    border: 1px solid #2a2a3e !important;
    border-radius: 4px !important;
}

/* Response codes - dark themed */
.swagger-ui .responses-wrapper { background: transparent !important; }
.swagger-ui .responses-inner { background: transparent !important; }
.swagger-ui .response-col_status { color: #4f8ef7 !important; font-weight: 600 !important; }
.swagger-ui .response-col_description { color: #c0c0c0 !important; }
.swagger-ui .response-col_links { color: #888 !important; }

/* Code blocks - JetBrains Mono */
.swagger-ui .highlight-code,
.swagger-ui .microlight,
.swagger-ui code,
.swagger-ui pre {
    font-family: 'JetBrains Mono', 'Fira Code', monospace !important;
    background: #0a0a14 !important;
    color: #c0c0c0 !important;
    border-radius: 6px !important;
    font-size: 13px !important;
}
.swagger-ui .microlight { padding: 12px !important; }

/* Response body */
.swagger-ui .responses-table {
    background: transparent !important;
}
.swagger-ui .response .response-col_description__inner div.markdown p { color: #c0c0c0 !important; }

/* Model/schema */
.swagger-ui .model-box { background: #111118 !important; }
.swagger-ui .model { color: #c0c0c0 !important; }
.swagger-ui .model-title { color: #fff !important; }
.swagger-ui .prop-type { color: #4f8ef7 !important; }

/* Try it out button */
.swagger-ui .btn.try-out__btn {
    border-color: #4f8ef7 !important;
    color: #4f8ef7 !important;
    border-radius: 6px !important;
}
.swagger-ui .btn.try-out__btn:hover {
    background: #4f8ef7 !important;
    color: #fff !important;
}

/* Execute button */
.swagger-ui .btn.execute {
    background: #4f8ef7 !important;
    color: #fff !important;
    border: none !important;
    border-radius: 6px !important;
    font-weight: 600 !important;
}

/* Cancel button */
.swagger-ui .btn.btn-clear {
    border-color: #666 !important;
    color: #999 !important;
    border-radius: 6px !important;
}

/* Lock icon in endpoint summary */
.swagger-ui .opblock-summary .authorization__btn { opacity: 0.8 !important; }

/* Loading */
.swagger-ui .loading-container .loading:after { color: #4f8ef7 !important; }

/* Scrollbar */
.swagger-ui ::-webkit-scrollbar { width: 6px; height: 6px; }
.swagger-ui ::-webkit-scrollbar-track { background: #0a0a0a; }
.swagger-ui ::-webkit-scrollbar-thumb { background: #2a2a3e; border-radius: 3px; }
"""

app = FastAPI(
    title="QuantumRand API",
    description=API_DESCRIPTION,
    version=API_VERSION,
    docs_url=None,
    redoc_url=None,
    lifespan=lifespan,
)


def custom_openapi():
    """Remove 422 Validation Error from all endpoint docs."""
    if app.openapi_schema:
        return app.openapi_schema
    from fastapi.openapi.utils import get_openapi
    schema = get_openapi(
        title=app.title, version=app.version,
        description=app.description, routes=app.routes,
    )
    for path in schema.get("paths", {}).values():
        for method in path.values():
            method.get("responses", {}).pop("422", None)
    # Remove ValidationError schema if unused
    schema.get("components", {}).get("schemas", {}).pop("ValidationError", None)
    schema.get("components", {}).get("schemas", {}).pop("HTTPValidationError", None)
    app.openapi_schema = schema
    return schema

app.openapi = custom_openapi

# CORS
origins = ALLOWED_ORIGINS if isinstance(ALLOWED_ORIGINS, list) else ALLOWED_ORIGINS.split(",")
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

engine = QuantumEngine()

# Mount static files
static_dir = Path(__file__).parent / "static"
if static_dir.exists():
    app.mount("/static", StaticFiles(directory=str(static_dir)), name="static")


# --- Custom docs route ---

@app.get("/docs", include_in_schema=False)
async def custom_swagger_ui():
    openapi_url = app.openapi_url or "/openapi.json"
    return HTMLResponse(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QuantumRand API Docs</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>Q</text></svg>">
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>{CUSTOM_CSS}</style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
    <script>
        SwaggerUIBundle({{
            url: "{openapi_url}",
            dom_id: '#swagger-ui',
            presets: [SwaggerUIBundle.presets.apis, SwaggerUIBundle.SwaggerUIStandalonePreset],
            layout: "BaseLayout",
            deepLinking: true,
            defaultModelsExpandDepth: -1,
            docExpansion: "list",
            persistAuthorization: true,
        }});
    </script>
</body>
</html>""")


# --- Middleware ---

@app.middleware("http")
async def request_logging(request: Request, call_next):
    start = time.perf_counter()
    response = await call_next(request)
    elapsed_ms = round((time.perf_counter() - start) * 1000, 2)
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    logger.info(f"{timestamp} | {request.method} | {request.url.path} | {response.status_code} | {elapsed_ms}ms")
    return response


# --- Global exception handler ---

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    if isinstance(exc, HTTPException):
        return JSONResponse(
            status_code=exc.status_code,
            content={"success": False, "error": exc.detail},
        )
    logger.error(f"Unhandled exception: {exc}")
    return JSONResponse(
        status_code=500,
        content={"success": False, "error": "Internal server error"},
    )


class KeyCreateRequest(BaseModel):
    name: str
    email: str
    tier: str = "free"


# --- Public endpoints ---

@app.get("/", response_class=HTMLResponse, summary="Landing Page",
         description="Serves the QuantumRand landing page.")
def landing_page():
    index_path = Path(__file__).parent / "static" / "index.html"
    if index_path.exists():
        return HTMLResponse(content=index_path.read_text())
    return HTMLResponse(content=f"<h1>{APP_NAME}</h1>")


@app.get("/api/info", summary="API Info",
         description="API version and status info. Returns available endpoints, version, and environment.")
def api_info():
    return {
        "success": True,
        "data": {
            "name": "QuantumRand API",
            "version": API_VERSION,
            "description": "Quantum Random Number Generator powered by Qiskit AerSimulator",
            "environment": ENV,
            "endpoints": [
                "GET  /              - Landing page",
                "GET  /api/info      - API info (public)",
                "GET  /health        - Health check (public)",
                "GET  /generate/bits - Generate random bits (auth required)",
                "GET  /generate/hex  - Generate random hex string (auth required)",
                "GET  /generate/integer - Generate random integer (auth required)",
                "POST /generate/key  - Generate cryptographic key (auth required)",
                "POST /keys/create   - Create new API key (public)",
                "GET  /keys/me       - Get your key info (auth required)",
                "GET  /keys/stats    - Get usage stats (auth required)",
            ],
        },
    }


@app.get("/health", summary="Health Check",
         description="System health check for all components. Returns status of database, quantum engine, uptime, and environment.")
def health():
    uptime_seconds = round(time.time() - START_TIME, 2)
    db_ok = check_connection()
    engine_result = engine.health_check()
    engine_ok = engine_result.get("status") == "healthy"
    overall = "healthy" if (db_ok and engine_ok) else "unhealthy"
    status_code = 200 if overall == "healthy" else 503

    return JSONResponse(
        status_code=status_code,
        content={
            "success": overall == "healthy",
            "data": {
                "status": overall,
                "environment": ENV,
                "version": API_VERSION,
                "uptime_seconds": uptime_seconds,
                "database": "connected" if db_ok else "disconnected",
                "quantum_engine": "healthy" if engine_ok else "unhealthy",
            },
        },
    )


@app.get("/backends", summary="List Backends",
         description="List all available quantum backends and their status. Includes local simulator and Origin Quantum cloud/hardware options.")
def list_backends():
    return {
        "success": True,
        "data": {
            "backends": engine._available_backends(),
            "default": "aer_simulator",
        },
    }


# --- Key management endpoints ---

@app.post("/keys/create", summary="Create API Key",
          description="Create a free API key instantly. Provide a name, email, and optional tier (free/indie/startup/business).")
def keys_create(body: KeyCreateRequest):
    try:
        result = create_api_key(body.name, body.email, body.tier)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    return {"success": True, "data": result}


@app.get("/keys/me", summary="My Key Info",
         description="View your key details and tier. Returns name, email, tier, active status, creation date, and rate limits.")
def keys_me(key_record: dict = Depends(require_api_key)):
    return {
        "success": True,
        "data": {
            "name": key_record["name"],
            "email": key_record["email"],
            "tier": key_record["tier"],
            "is_active": bool(key_record["is_active"]),
            "created_at": key_record["created_at"],
            "last_used_at": key_record["last_used_at"],
            "rate_limit": TIER_LIMITS[key_record["tier"]],
        },
    }


@app.get("/keys/stats", summary="Usage Statistics",
         description="View your usage statistics. Returns total calls, total bits generated, calls today, and calls this month.")
def keys_stats(key_record: dict = Depends(require_api_key)):
    stats = get_usage_stats(key_record["key"])
    stats["tier"] = key_record["tier"]
    stats["rate_limit"] = TIER_LIMITS[key_record["tier"]]
    return {"success": True, "data": stats}


# --- Admin endpoints ---

@app.get("/admin/{secret}/keys", summary="List All API Keys (Admin)",
         description="Admin-only: list all API keys.",
         include_in_schema=False)
def admin_list_keys(secret: str):
    if secret != ADMIN_SECRET:
        raise HTTPException(status_code=403, detail="Invalid admin secret")
    keys = list_all_keys()
    return {"success": True, "data": {"total": len(keys), "keys": keys}}


# --- Authenticated generate endpoints ---

def _log_and_update(api_key: str, endpoint: str, bits: int, elapsed_ms: float):
    log_usage(api_key, endpoint, bits, elapsed_ms)
    update_last_used(api_key)


@app.get("/generate/bits", summary="Generate Random Bits",
         description="Generate raw quantum random bits. Specify count with `n` (1-4096). Optionally choose a `backend` (aer_simulator, origin_cloud, origin_wuyuan).")
def generate_bits(
    n: int = Query(default=256, ge=1, le=4096),
    backend: str = Query(default="aer_simulator", description="Quantum backend to use"),
    key_record: dict = Depends(require_api_key),
):
    if backend not in VALID_BACKENDS:
        raise HTTPException(status_code=400, detail=f"Invalid backend. Choose from: {VALID_BACKENDS}")
    max_bits = TIER_LIMITS[key_record["tier"]]["max_bits"]
    if n > max_bits:
        raise HTTPException(
            status_code=400,
            detail=f"Your '{key_record['tier']}' tier allows max {max_bits} bits per call.",
        )
    try:
        result = engine.generate_bits(n, backend)
    except (ValueError, RuntimeError) as e:
        raise HTTPException(status_code=400, detail=str(e))
    _log_and_update(key_record["key"], "/generate/bits", n, result["elapsed_ms"])
    return {"success": True, "data": result}


@app.get("/generate/hex", summary="Generate Random Hex",
         description="Generate a quantum random hex string. `n` must be a multiple of 4 (4-4096). Optionally choose a `backend`.")
def generate_hex(
    n: int = Query(default=256, ge=4, le=4096),
    backend: str = Query(default="aer_simulator", description="Quantum backend to use"),
    key_record: dict = Depends(require_api_key),
):
    if backend not in VALID_BACKENDS:
        raise HTTPException(status_code=400, detail=f"Invalid backend. Choose from: {VALID_BACKENDS}")
    if n % 4 != 0:
        raise HTTPException(status_code=400, detail="n must be a multiple of 4")
    max_bits = TIER_LIMITS[key_record["tier"]]["max_bits"]
    if n > max_bits:
        raise HTTPException(
            status_code=400,
            detail=f"Your '{key_record['tier']}' tier allows max {max_bits} bits per call.",
        )
    try:
        result = engine.generate_bits(n, backend)
    except (ValueError, RuntimeError) as e:
        raise HTTPException(status_code=400, detail=str(e))
    _log_and_update(key_record["key"], "/generate/hex", n, result["elapsed_ms"])
    return {
        "success": True,
        "data": {
            "hex": result["hex"],
            "num_bits": n,
            "elapsed_ms": result["elapsed_ms"],
            "source": result["source"],
        },
    }


@app.get("/generate/integer", summary="Generate Random Integer",
         description="Generate a quantum random integer in a given range. Uses rejection sampling for uniform distribution. Optionally choose a `backend`.")
def generate_integer(
    min: int = Query(default=0),
    max: int = Query(default=100),
    backend: str = Query(default="aer_simulator", description="Quantum backend to use"),
    key_record: dict = Depends(require_api_key),
):
    if backend not in VALID_BACKENDS:
        raise HTTPException(status_code=400, detail=f"Invalid backend. Choose from: {VALID_BACKENDS}")
    if min >= max:
        raise HTTPException(status_code=400, detail="min must be less than max")
    try:
        result = engine.generate_integer(min, max, backend)
    except (ValueError, RuntimeError) as e:
        raise HTTPException(status_code=400, detail=str(e))
    _log_and_update(key_record["key"], "/generate/integer", result["bits_used"], result["elapsed_ms"])
    return {"success": True, "data": result}


@app.post("/generate/key", summary="Generate Cryptographic Key",
          description="Generate a cryptographic key using quantum randomness. Supports 128, 192, 256, or 512 bit keys. Optionally choose a `backend`.")
def generate_key(
    bits: int = Query(default=256),
    backend: str = Query(default="aer_simulator", description="Quantum backend to use"),
    key_record: dict = Depends(require_api_key),
):
    if backend not in VALID_BACKENDS:
        raise HTTPException(status_code=400, detail=f"Invalid backend. Choose from: {VALID_BACKENDS}")
    max_bits = TIER_LIMITS[key_record["tier"]]["max_bits"]
    if bits > max_bits:
        raise HTTPException(
            status_code=400,
            detail=f"Your '{key_record['tier']}' tier allows max {max_bits} bits per call.",
        )
    try:
        result = engine.generate_key(bits, backend)
    except (ValueError, RuntimeError) as e:
        raise HTTPException(status_code=400, detail=str(e))
    _log_and_update(key_record["key"], "/generate/key", bits, result["elapsed_ms"])
    return {"success": True, "data": result}
